version: '3.8'
services:
  ytclipper:
    build: .
    ports:
      - "8080:8080"
    environment:
      - YTCLIPPER_PORT=8080
      - YTCLIPPER_DEBUG=false
      - YTCLIPPER_RATE_LIMITER_RATE=5
    volumes:
      - ./videos:/app/videos
    restart: unless-stopped