name: Build and Test (Development)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      YTCLIPPER_YT_DLP_PROXY: ${{ secrets.YTDLP_PROXY_URL }}
      YTCLIPPER_CLIP_CLEANUP_SCHEDULER_ENABLED: "false"
      GO_VERSION: "1.23" 
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 
        
      - name: Set Up Go
        uses: actions/setup-go@v5  
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true 
          
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make \
            python3 \
            python3-pip \
            ffmpeg \
            google-chrome-stable
            
      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade \
            yt-dlp \
            requests \
            curl_cffi \
            urllib3
            
      - name: Install Go Dependencies
        run: go mod tidy
        
      - name: Build Production
        run: make build-prod
