name: Build and Test (Development)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      YTCLIPPER_CLIP_CLEANUP_SCHEDULER_ENABLED: "false"
      YTCLIPPER_YT_DLP_EXTRACTOR_RETRIES: "1"
      YTCLIPPER_YT_DLP_SLEEP_INTERVAL: "1"
      YTCLIPPER_YT_DLP_ENABLE_USER_AGENT_ROTATION: "true"
      YTCLIPPER_YT_DLP_COOKIES_FILE: ""
      YTCLIPPER_YT_DLP_PROXY: ""
      GO_VERSION: "1.23" 
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 
        
      - name: Set Up Go
        uses: actions/setup-go@v5  
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true 
          
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            make \
            python3 \
            python3-pip \
            ffmpeg \
            google-chrome-stable
            
      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade \
            yt-dlp \
            requests \
            curl_cffi \
            urllib3
            
      - name: Setup Cookie-Free Configuration
        run: |
          # No cookies or proxy needed - using enhanced user agent rotation
          echo "Using cookie-free and proxy-free configuration with enhanced anti-detection"
          echo "User agent rotation: enabled"
          echo "Sleep interval: 1 second"
            
      - name: Install Go Dependencies
        run: go mod tidy
        
      - name: Build Production
        run: make build-prod
